import ex
num = int(input("digite um número para a efetuação da tabuada: "))
print('-'*12)
print(f'1 x {num:2} =', num*1)
print(f'2 x {num:2} =', num*2)
print(f'3 x {num:2} =', num*3)
print(f'4 x {num:2} =', num*4)
print(f'5 x {num:2} =', num*5)
print(f'6 x {num:2} =', num*6)
print(f'7 x {num:2} =', num*7)
print(f'8 x {num:2} =', num*8)
print(f'9 x {num:2} =', num*9)
print(f'10 x {num} =', num*10)
print('-'*12)